steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-f','dockerfiles/backend.dockerfile', '-t', 'gcr.io/ml-ops-ex/deployment']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml-ops-ex/deployment']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'deployment-prediction-model'
  - '--image'
  - 'gcr.io/ml-ops-ex/:latest'
  - '--region'
  - ' europe-north1'
  - '--update-secrets=/etc/secret/=prediction-gbucket-secret:latest'
images:
  - 'gcr.io/your-project-id/your-image-name:your-tag'