steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f','dockerfiles/backend.dockerfile', '-t', 'gcr.io/ml-ops-ex/deployment']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml-ops-ex/deployment']