google_cloud:
  bucket_name : prediction-model-bucket
  model_blob_name : trained_model_out.ckpt
  key_file_name : prediction_model_bucket_service_account_key_file.json
local_model_file_name : prediction_model.ckpt