steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', 'train_model.dockerfile', '-t', 'gcr.io/ml-ops-ex/testing', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml-ops-ex/testing']
